# LATIHAN ARRAY

In [8]:

# perkalaian matriks array

import numpy as np
A = np.array([22, 12, 24])
B = np.array([26, 84, 66])

perkalian = A * B
print("perkalaian matriks array:")
print(perkalian)


perkalaian matriks array:
[ 572 1008 1584]


In [9]:
# pengurangan matriks array

import numpy as np
A = np.array([22, 12, 24])
B = np.array([26, 84, 66])

pengurangan = B - A
print("pengurangan matriks array:")
print(pengurangan)


pengurangan matriks array:
[ 4 72 42]


In [5]:
# transpose matriks arrsy

import numpy as np

A = np.array([[22, 12, 24,], [26, 84, 66]])

transpose_A = np.transpose(A)
print("transpose matriks array:")
print(transpose_A)


transpose matriks array:
[[22 26]
 [12 84]
 [24 66]]


In [14]:
# invers matriks array

import numpy as np

A = np.array([[22,12],[84,66]])

invers_A = np.linalg.inv(A)
print("invers matriks A:")
print(invers_A)

invers matriks A:
[[ 0.14864865 -0.02702703]
 [-0.18918919  0.04954955]]


In [12]:
# determinan matriks array

import numpy as np
A = np.array([[22,12],[84,66]])

determinant_A = np.linalg.det(A)
print("nilai determinan:")
print("determinan dari matriks A:", determinant_A)

nilai determinan:
determinan dari matriks A: 443.9999999999996
